### ISSUE TITLE
Should syl components be generated even when text is not present?

### ISSUE THREAD

**Issue by noahbaxter** [DDMAL/JSOMR2MEI#6]
All syllables should always have lyrics, so syl is expected to always exist. Currently however, no lyric information is given. Should this be generated as a generic tag even when its content can't be properly generated?

Currently they are not being generated.

**Comment by fujinaga** [comment]
How about generating a blank space for each <neume>? The lyrics will be filled in elsewhere in the Rodan workflow.

**Comment by vigliensoni** [comment]
<neume> is a child of <syllable> not from <syl>.

I think there is no need of encoding <syl> at this point.



On Fri, Jun 8, 2018 at 11:58 AM, Ichiro Fujinaga notifications@github.com
wrote:
>

How about generating a blank space for each ? The lyrics will be
filled in elsewhere in the Rodan workflow.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
​
